### ISSUE TITLE
tried updating to handle TF 1.1 under Python3 v3.6 on Windows

### ISSUE THREAD

**Issue by jayprich** [cvxgrp/cvxflow#2]
changes "concat" arg order, "reverse" axis list, "pack" -> "stack" and "mul" to "scalar_mul" were necessary
```DOS
C:\Users\tatli\Downloads\WinPython-64bit-3.6.0.1Qt5b5\scripts>python c:\Users\tatli\cvxflow\cvxflow\problem_test.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.428s

OK
```
[diff_changes.txt](https://github.com/cvxgrp/cvxflow/files/1055471/diff_changes.txt)

**Comment by mwytock** [comment]
Nice - submit a pull request?

**Comment by jayprich** [comment]
well bear in mind that these TensorFlow's API changes are breaking changes
if you'd like me to do that then please let me know how (i.e. talk me through a pull request)
